name: Respond to Pull Request

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: job name
        if: github.event.review.state == 'approved'
        run: |
          echo "approved"